- name: Install Mosquito packages
  apt:
    name: "{{ packages }}"
    update_cache: no
  become: yes
  vars:
    packages:
    - mosquitto
    - mosquitto-clients
    - certbot

- name: Create letsencrypt certificate kekskurse.ddns.net
  shell: certbot certonly --standalone  --agree-tos -m letsencrqpt@kekskurse.de -d kekskurse.ddns.net
  args:
      creates: /etc/letsencrypt/live/kekskurse.ddns.net
  become: yes

- name: Create file
  command: touch /etc/mosquitto/passwd
  args:
    creates: /etc/mosquitto/passwd

- name: Add letsencrypt cronjob for cert renewal
  become: yes
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: certbot renew --noninteractive --post-hook "systemctl restart mosquitto"

- copy:
    src: "{{ role_path }}/files/mosquito_config.conf"
    dest: /etc/mosquitto/conf.d/default.conf
  become: yes

- service: name=mosquitto state=restarted enabled=yes
  become: yes
