- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  become: yes
  vars:
    packages:
    - zsh
    - vim
- name: Download grml config
  get_url:
    url: https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
    dest: ~/.zshrc
    mode: 0660
  become: true
- name: Change user pi to zsh
  user:
    name: pi
    shell: /bin/zsh
  become: yes
- name: Disable password login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^(#\s*)?PasswordAuthentication " line="PasswordAuthentication no"
  notify: restart sshd
  become: yes
