- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  become: yes
  vars:
    packages:
    - zsh
    - vim
- name: Download grml config
  get_url:
    url: https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
    dest: /etc/zsh/zshrc
    mode: 0666
  become: true
- name: Change user pi to zsh
  user:
    name: pi
    shell: /bin/zsh
  become: yes
