- name: Install PeerVPN packages
  apt:
    name: "{{ packages }}"
    update_cache: no
  become: yes
  vars:
    packages:
    - libssl1.0-dev
    - make
    - git
    - gcc

- name: Check if PeerVPN exists
  stat: 
    path: /usr/local/sbin/peervpn
  register: peervpn_exists

- git:
    repo: https://github.com/Nayar/peervpn
    dest: /home/pi/peervpn
    accept_hostkey: yes
  when: peervpn_exists.stat.exists == false

- name: Make PeerVPN
  shell: make
  args:
    chdir: /home/pi/peervpn
  when: peervpn_exists.stat.exists == false

- name: Make install PeerVPN
  shell: make install
  become: yes
  args:
    chdir: /home/pi/peervpn
  when: peervpn_exists.stat.exists == false